# Generated by the protoc compiler with a custom plugin. DO NOT EDIT!
# sources: opentelemetry/proto/collector/logs/v1/logs_service.proto

from __future__ import annotations

import struct
from typing import List

from snowflake.telemetry._internal.opentelemetry.proto.logs.v1.logs_marshaler import *
from snowflake.telemetry._internal.serialize import (
    Enum,
    MessageMarshaler,
    Varint,
)


class ExportLogsServiceRequest(MessageMarshaler):
    @property
    def resource_logs(self) -> List[ResourceLogs]:
        if self._resource_logs is None:
            self._resource_logs = list()
        return self._resource_logs

    def __init__(
        self,
        resource_logs: List[ResourceLogs] = None,
    ):
        self._resource_logs: List[ResourceLogs] = resource_logs
        self._marshaler_cache = {}

    def calculate_size(self) -> int:
        size = 0
        if self._resource_logs:
            size += sum(
                message._get_size()
                + len(b"\n")
                + Varint.size_varint_u32(message._get_size())
                for message in self._resource_logs
            )
        return size

    def write_to(self, out: bytearray) -> None:
        if self._resource_logs:
            for v in self._resource_logs:
                out += b"\n"
                Varint.write_varint_u32(out, v._get_size())
                v.write_to(out)


class ExportLogsServiceResponse(MessageMarshaler):
    @property
    def partial_success(self) -> ExportLogsPartialSuccess:
        if self._partial_success is None:
            self._partial_success = ExportLogsPartialSuccess()
        return self._partial_success

    def __init__(
        self,
        partial_success: ExportLogsPartialSuccess = None,
    ):
        self._partial_success: ExportLogsPartialSuccess = partial_success
        self._marshaler_cache = {}

    def calculate_size(self) -> int:
        size = 0
        if self._partial_success is not None:
            size += (
                len(b"\n")
                + Varint.size_varint_u32(self._partial_success._get_size())
                + self._partial_success._get_size()
            )
        return size

    def write_to(self, out: bytearray) -> None:
        if self._partial_success is not None:
            out += b"\n"
            Varint.write_varint_u32(out, self._partial_success._get_size())
            self._partial_success.write_to(out)


class ExportLogsPartialSuccess(MessageMarshaler):
    rejected_log_records: int
    error_message: str

    def __init__(
        self,
        rejected_log_records: int = 0,
        error_message: str = "",
    ):
        self.rejected_log_records: int = rejected_log_records
        self.error_message: str = error_message
        self._marshaler_cache = {}

    def calculate_size(self) -> int:
        size = 0
        if self.rejected_log_records:
            size += len(b"\x08") + Varint.size_varint_i64(self.rejected_log_records)
        if self.error_message:
            v = self.error_message.encode("utf-8")
            self._marshaler_cache[b"\x12"] = v
            size += len(b"\x12") + Varint.size_varint_u32(len(v)) + len(v)
        return size

    def write_to(self, out: bytearray) -> None:
        if self.rejected_log_records:
            out += b"\x08"
            Varint.write_varint_i64(out, self.rejected_log_records)
        if self.error_message:
            v = self._marshaler_cache[b"\x12"]
            out += b"\x12"
            Varint.write_varint_u32(out, len(v))
            out += v
