# Generated by the protoc compiler with a custom plugin. DO NOT EDIT!
# sources: opentelemetry/proto/collector/logs/v1/logs_service.proto

from typing import (
    List,
    Optional,
)

from snowflake.telemetry._internal.serialize import (
    Enum,
    ProtoSerializer,
)


def ExportLogsServiceRequest(
    resource_logs: Optional[List[bytes]] = None,
) -> bytes:
    proto_serializer = ProtoSerializer()
    if resource_logs:
        proto_serializer.serialize_repeated_message(b"\n", resource_logs)
    return proto_serializer.out


def ExportLogsServiceResponse(
    partial_success: Optional[bytes] = None,
) -> bytes:
    proto_serializer = ProtoSerializer()
    if partial_success is not None:
        proto_serializer.serialize_message(b"\n", partial_success)
    return proto_serializer.out


def ExportLogsPartialSuccess(
    rejected_log_records: Optional[int] = None,
    error_message: Optional[str] = None,
) -> bytes:
    proto_serializer = ProtoSerializer()
    if rejected_log_records:
        proto_serializer.serialize_int64(b"\x08", rejected_log_records)
    if error_message:
        proto_serializer.serialize_string(b"\x12", error_message)
    return proto_serializer.out
