{% set name = "opentelemetry-sdk" %}
{% set version = "1.38.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/2f/2e/e93777a95d7d9c40d270a371392b6d6f1ff170c2a3cb32d6176741b5b723/opentelemetry_sdk-{{ version }}-py3-none-any.whl

build:
  number: 0
  noarch: python
  script: |
    {{ PYTHON }} -m pip install *.whl --no-deps --target={{ SP_DIR }} -vvv
    {{ PYTHON }} -m compileall -f -q {{ SP_DIR }}/opentelemetry

requirements:
  build:
    - python
    - pip
  host:
    - python
    - pip
  run:
    - python >=3.8
    - opentelemetry-api ==1.38.0
    - opentelemetry-semantic-conventions ==0.59b0
    - typing_extensions >=3.7.4

about:
  home: https://opentelemetry.io/
  license: Apache-2.0
  summary: OpenTelemetry Python SDK (with .pyc files pre-compiled)
