package:
    name: snowflake_telemetry_python
    version: "0.5.0"

source:
    path: {{ environ.get('SNOWFLAKE_TELEMETRY_DIR') }}

requirements:
    build:
        - python
        - setuptools >=40.0.0
    run:
        - python
        - opentelemetry-api ==1.23.0
        - opentelemetry-exporter-otlp-proto-common ==1.23.0
        - opentelemetry-sdk ==1.23.0

about:
    home: https://www.snowflake.com/
    license: Apache 2.0
    license_file: {{ environ.get('SNOWFLAKE_TELEMETRY_DIR') }}/LICENSE.txt
    summary: Snowflake Telemetry Python package
