package:
    name: snowflake-telemetry-python
    version: "0.6.1"

source:
    path: {{ environ.get('SNOWFLAKE_TELEMETRY_DIR') }}

build:
  noarch: python

requirements:
    build:
        - python
        - setuptools >=40.0.0
    run:
        - python
        - opentelemetry-api ==1.26.0
        - opentelemetry-sdk ==1.26.0

about:
    home: https://www.snowflake.com/
    license: Apache 2.0
    license_file: {{ environ.get('SNOWFLAKE_TELEMETRY_DIR') }}/LICENSE.txt
    summary: Snowflake Telemetry Python package
