package:
    name: snowflake_telemetry_python
    version: "0.1.0"

source:
    path: /tmp/anaconda_workspace/src

requirements:
    build:
        - python
        - setuptools >=40.0.0
    run:
        - python
        - opentelemetry-api ==1.12.0
        - opentelemetry-sdk ==1.12.0
        - opentelemetry-exporter-otlp ==1.12.0

about:
    home: https://www.snowflake.com/
    license: Apache 2.0
    license_file: /tmp/anaconda_workspace/src/LICENSE.txt
    summary: Snowflake Telemetry Python package 

