# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources:
# plugin: python-serialize

from typing import List

from snowflake.telemetry.serialize import (
    Enum,
    MessageMarshaler,
    ProtoSerializer,
)


class ExportTraceServiceRequest(MessageMarshaler):
    def __init__(
        self,
        resource_spans: List[MessageMarshaler] = None,
    ):
        self.resource_spans = resource_spans

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.resource_spans:
            proto_serializer.serialize_repeated_message(b"\n", self.resource_spans)


class ExportTraceServiceResponse(MessageMarshaler):
    def __init__(
        self,
        partial_success: MessageMarshaler = None,
    ):
        self.partial_success = partial_success

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.partial_success:
            proto_serializer.serialize_message(b"\n", self.partial_success)


class ExportTracePartialSuccess(MessageMarshaler):
    def __init__(
        self,
        rejected_spans: int = 0,
        error_message: str = "",
    ):
        self.rejected_spans = rejected_spans
        self.error_message = error_message

    def write_to(self, proto_serializer: ProtoSerializer) -> None:
        if self.error_message:
            proto_serializer.serialize_string(b"\x12", self.error_message)
        if self.rejected_spans:
            proto_serializer.serialize_int64(b"\x08", self.rejected_spans)
