# Generated by the protoc compiler with a custom plugin. DO NOT EDIT!
# sources: opentelemetry/proto/resource/v1/resource.proto

from __future__ import annotations

import struct
from io import BytesIO
from typing import (
    List,
    Optional,
)

from snowflake.telemetry._internal.opentelemetry.proto.common.v1 import *
from snowflake.telemetry._internal.serialize import (
    Enum,
    MessageMarshaler,
    size_varint32,
    size_varint64,
    write_varint_unsigned,
)


class Resource(MessageMarshaler):
    def __init__(
        self,
        attributes: List[KeyValue] = None,
        dropped_attributes_count: int = 0,
    ):
        self.attributes: List[KeyValue] = attributes
        self.dropped_attributes_count: int = dropped_attributes_count

    def calculate_size(self) -> int:
        size = 0
        if self.attributes:
            size += sum(
                message._get_size() + len(b"\n") + size_varint32(message._get_size())
                for message in self.attributes
            )
        if self.dropped_attributes_count:
            size += len(b"\x10") + size_varint32(self.dropped_attributes_count)
        return size

    def write_to(self, out: BytesIO) -> None:
        if self.attributes:
            for v in self.attributes:
                out += b"\n"
                write_varint_unsigned(out, v._get_size())
                v.write_to(out)
        if self.dropped_attributes_count:
            out += b"\x10"
            write_varint_unsigned(out, self.dropped_attributes_count)
