# Generated by the protoc compiler with a custom plugin. DO NOT EDIT!
# sources: opentelemetry/proto/resource/v1/resource.proto

from typing import (
    List,
    Optional,
)

from snowflake.telemetry._internal.serialize import (
    Enum,
    ProtoSerializer,
)


def Resource(
    attributes: Optional[List[bytes]] = None,
    dropped_attributes_count: Optional[int] = None,
) -> bytes:
    proto_serializer = ProtoSerializer()
    if attributes:
        proto_serializer.serialize_repeated_message(b"\n", attributes)
    if dropped_attributes_count:
        proto_serializer.serialize_uint32(b"\x10", dropped_attributes_count)
    return proto_serializer.out
